<!DOCTYPE html>
<html>

<head>
    <style>
        body {
            font-family: sans-serif;
            line-height: 1.6;
            color: #333;
        }

        .container {
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
            border: 1px solid #eee;
        }

        .header {
            border-bottom: 2px solid #7c3aed;
            padding-bottom: 10px;
            margin-bottom: 20px;
        }

        .stat-item {
            margin-bottom: 15px;
        }

        .label {
            font-weight: bold;
            color: #666;
        }

        .value {
            font-size: 1.2em;
            font-weight: bold;
            color: #7c3aed;
        }

        .footer {
            margin-top: 30px;
            font-size: 0.8em;
            color: #999;
            border-top: 1px solid #eee;
            padding-top: 10px;
        }
    </style>
</head>

<body>
    <div class="container">
        <div class="header">
            <h2>Daily Performance Report</h2>
            <p>{{ now()->format('l, F j, Y') }}</p>
        </div>

        <div class="stat-item">
            <div class="label">Total Earned Today</div>
            <div class="value">${{ number_format($stats['total_revenue'], 2) }}</div>
        </div>

        <div class="stat-item">
            <div class="label">Total Sold Today</div>
            <div class="value">{{ $stats['items_count'] ?? 0 }} units</div>
        </div>

        <div class="stat-item">
            <div class="label">Best Performing Stock</div>
            <div class="value">{{ $stats['best_product'] }}</div>
        </div>

        <div class="stat-item">
            <div class="label">Best Category</div>
            <div class="value">
                @php
                    $bestCategory = count($stats['top_categories']) > 0 ? array_key_first($stats['top_categories']) : 'None';
                @endphp
                {{ $bestCategory }}
            </div>
        </div>

        <div class="footer">
            This report was automatically generated by the Marketplace system.
        </div>
    </div>
</body>

</html>